//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 04:49:26 PM EDT 
//


package com.hackathon.QBDemo.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IsFiling1099Misc" minOccurs="0"/>
 *         &lt;element ref="{}FormType" minOccurs="0"/>
 *         &lt;element ref="{}CategoryAccountMappingMod" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isFiling1099Misc",
    "formType",
    "categoryAccountMappingMod"
})
@XmlRootElement(name = "Form1099CategoryAccountMappingMod")
public class Form1099CategoryAccountMappingMod {

    @XmlElement(name = "IsFiling1099Misc")
    protected String isFiling1099Misc;
    @XmlElement(name = "FormType")
    protected String formType;
    @XmlElement(name = "CategoryAccountMappingMod")
    protected List<CategoryAccountMappingMod> categoryAccountMappingMod;

    /**
     * Gets the value of the isFiling1099Misc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFiling1099Misc() {
        return isFiling1099Misc;
    }

    /**
     * Sets the value of the isFiling1099Misc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFiling1099Misc(String value) {
        this.isFiling1099Misc = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    /**
     * Gets the value of the categoryAccountMappingMod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryAccountMappingMod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryAccountMappingMod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryAccountMappingMod }
     * 
     * 
     */
    public List<CategoryAccountMappingMod> getCategoryAccountMappingMod() {
        if (categoryAccountMappingMod == null) {
            categoryAccountMappingMod = new ArrayList<CategoryAccountMappingMod>();
        }
        return this.categoryAccountMappingMod;
    }

}
