//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 04:49:26 PM EDT 
//


package com.hackathon.QBDemo.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TxnLineID"/>
 *         &lt;element ref="{}ItemRef" minOccurs="0"/>
 *         &lt;element ref="{}FromInventorySiteLocationRef" minOccurs="0"/>
 *         &lt;element ref="{}ToInventorySiteLocationRef" minOccurs="0"/>
 *         &lt;element ref="{}QuantityTransferred" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SerialNumber" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{}STRTYPE">
 *                 &lt;maxLength value="4095"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="LotNumber" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{}STRTYPE">
 *                 &lt;maxLength value="40"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "txnLineID",
    "itemRef",
    "fromInventorySiteLocationRef",
    "toInventorySiteLocationRef",
    "quantityTransferred",
    "serialNumber",
    "lotNumber"
})
@XmlRootElement(name = "TransferInventoryLineRet")
public class TransferInventoryLineRet {

    @XmlElement(name = "TxnLineID", required = true)
    protected String txnLineID;
    @XmlElement(name = "ItemRef")
    protected ItemRef itemRef;
    @XmlElement(name = "FromInventorySiteLocationRef")
    protected FromInventorySiteLocationRef fromInventorySiteLocationRef;
    @XmlElement(name = "ToInventorySiteLocationRef")
    protected ToInventorySiteLocationRef toInventorySiteLocationRef;
    @XmlElement(name = "QuantityTransferred")
    protected String quantityTransferred;
    @XmlElement(name = "SerialNumber")
    protected String serialNumber;
    @XmlElement(name = "LotNumber")
    protected String lotNumber;

    /**
     * Gets the value of the txnLineID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnLineID() {
        return txnLineID;
    }

    /**
     * Sets the value of the txnLineID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnLineID(String value) {
        this.txnLineID = value;
    }

    /**
     * Gets the value of the itemRef property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRef }
     *     
     */
    public ItemRef getItemRef() {
        return itemRef;
    }

    /**
     * Sets the value of the itemRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRef }
     *     
     */
    public void setItemRef(ItemRef value) {
        this.itemRef = value;
    }

    /**
     * Gets the value of the fromInventorySiteLocationRef property.
     * 
     * @return
     *     possible object is
     *     {@link FromInventorySiteLocationRef }
     *     
     */
    public FromInventorySiteLocationRef getFromInventorySiteLocationRef() {
        return fromInventorySiteLocationRef;
    }

    /**
     * Sets the value of the fromInventorySiteLocationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromInventorySiteLocationRef }
     *     
     */
    public void setFromInventorySiteLocationRef(FromInventorySiteLocationRef value) {
        this.fromInventorySiteLocationRef = value;
    }

    /**
     * Gets the value of the toInventorySiteLocationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ToInventorySiteLocationRef }
     *     
     */
    public ToInventorySiteLocationRef getToInventorySiteLocationRef() {
        return toInventorySiteLocationRef;
    }

    /**
     * Sets the value of the toInventorySiteLocationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToInventorySiteLocationRef }
     *     
     */
    public void setToInventorySiteLocationRef(ToInventorySiteLocationRef value) {
        this.toInventorySiteLocationRef = value;
    }

    /**
     * Gets the value of the quantityTransferred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityTransferred() {
        return quantityTransferred;
    }

    /**
     * Sets the value of the quantityTransferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityTransferred(String value) {
        this.quantityTransferred = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the lotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotNumber() {
        return lotNumber;
    }

    /**
     * Sets the value of the lotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotNumber(String value) {
        this.lotNumber = value;
    }

}
