//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 04:49:26 PM EDT 
//


package com.hackathon.QBDemo.model.qbXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EnhancedInventoryReceivingEnabled" minOccurs="0"/>
 *         &lt;element ref="{}IsTrackingSerialOrLotNumber" minOccurs="0"/>
 *         &lt;element ref="{}isTrackingOnSalesTransactionsEnabled" minOccurs="0"/>
 *         &lt;element ref="{}isTrackingOnPurchaseTransactionsEnabled" minOccurs="0"/>
 *         &lt;element ref="{}isTrackingOnInventoryAdjustmentEnabled" minOccurs="0"/>
 *         &lt;element ref="{}isTrackingOnBuildAssemblyEnabled" minOccurs="0"/>
 *         &lt;element ref="{}FIFOEnabled" minOccurs="0"/>
 *         &lt;element ref="{}FIFOEffectiveDate" minOccurs="0"/>
 *         &lt;element ref="{}IsRSBEnabled" minOccurs="0"/>
 *         &lt;element ref="{}IsBarcodeEnabled" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enhancedInventoryReceivingEnabled",
    "isTrackingSerialOrLotNumber",
    "isTrackingOnSalesTransactionsEnabled",
    "isTrackingOnPurchaseTransactionsEnabled",
    "isTrackingOnInventoryAdjustmentEnabled",
    "isTrackingOnBuildAssemblyEnabled",
    "fifoEnabled",
    "fifoEffectiveDate",
    "isRSBEnabled",
    "isBarcodeEnabled"
})
@XmlRootElement(name = "ItemsAndInventoryPreferences")
public class ItemsAndInventoryPreferences {

    @XmlElement(name = "EnhancedInventoryReceivingEnabled")
    protected String enhancedInventoryReceivingEnabled;
    @XmlElement(name = "IsTrackingSerialOrLotNumber", defaultValue = "None")
    protected String isTrackingSerialOrLotNumber;
    protected String isTrackingOnSalesTransactionsEnabled;
    protected String isTrackingOnPurchaseTransactionsEnabled;
    protected String isTrackingOnInventoryAdjustmentEnabled;
    protected String isTrackingOnBuildAssemblyEnabled;
    @XmlElement(name = "FIFOEnabled")
    protected String fifoEnabled;
    @XmlElement(name = "FIFOEffectiveDate")
    protected String fifoEffectiveDate;
    @XmlElement(name = "IsRSBEnabled")
    protected String isRSBEnabled;
    @XmlElement(name = "IsBarcodeEnabled")
    protected String isBarcodeEnabled;

    /**
     * Gets the value of the enhancedInventoryReceivingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedInventoryReceivingEnabled() {
        return enhancedInventoryReceivingEnabled;
    }

    /**
     * Sets the value of the enhancedInventoryReceivingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedInventoryReceivingEnabled(String value) {
        this.enhancedInventoryReceivingEnabled = value;
    }

    /**
     * Gets the value of the isTrackingSerialOrLotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingSerialOrLotNumber() {
        return isTrackingSerialOrLotNumber;
    }

    /**
     * Sets the value of the isTrackingSerialOrLotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingSerialOrLotNumber(String value) {
        this.isTrackingSerialOrLotNumber = value;
    }

    /**
     * Gets the value of the isTrackingOnSalesTransactionsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingOnSalesTransactionsEnabled() {
        return isTrackingOnSalesTransactionsEnabled;
    }

    /**
     * Sets the value of the isTrackingOnSalesTransactionsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingOnSalesTransactionsEnabled(String value) {
        this.isTrackingOnSalesTransactionsEnabled = value;
    }

    /**
     * Gets the value of the isTrackingOnPurchaseTransactionsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingOnPurchaseTransactionsEnabled() {
        return isTrackingOnPurchaseTransactionsEnabled;
    }

    /**
     * Sets the value of the isTrackingOnPurchaseTransactionsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingOnPurchaseTransactionsEnabled(String value) {
        this.isTrackingOnPurchaseTransactionsEnabled = value;
    }

    /**
     * Gets the value of the isTrackingOnInventoryAdjustmentEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingOnInventoryAdjustmentEnabled() {
        return isTrackingOnInventoryAdjustmentEnabled;
    }

    /**
     * Sets the value of the isTrackingOnInventoryAdjustmentEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingOnInventoryAdjustmentEnabled(String value) {
        this.isTrackingOnInventoryAdjustmentEnabled = value;
    }

    /**
     * Gets the value of the isTrackingOnBuildAssemblyEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingOnBuildAssemblyEnabled() {
        return isTrackingOnBuildAssemblyEnabled;
    }

    /**
     * Sets the value of the isTrackingOnBuildAssemblyEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingOnBuildAssemblyEnabled(String value) {
        this.isTrackingOnBuildAssemblyEnabled = value;
    }

    /**
     * Gets the value of the fifoEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIFOEnabled() {
        return fifoEnabled;
    }

    /**
     * Sets the value of the fifoEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIFOEnabled(String value) {
        this.fifoEnabled = value;
    }

    /**
     * Gets the value of the fifoEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIFOEffectiveDate() {
        return fifoEffectiveDate;
    }

    /**
     * Sets the value of the fifoEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIFOEffectiveDate(String value) {
        this.fifoEffectiveDate = value;
    }

    /**
     * Gets the value of the isRSBEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRSBEnabled() {
        return isRSBEnabled;
    }

    /**
     * Sets the value of the isRSBEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRSBEnabled(String value) {
        this.isRSBEnabled = value;
    }

    /**
     * Gets the value of the isBarcodeEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsBarcodeEnabled() {
        return isBarcodeEnabled;
    }

    /**
     * Sets the value of the isBarcodeEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsBarcodeEnabled(String value) {
        this.isBarcodeEnabled = value;
    }

}
